name: ci

on:
    push:
        branches: [master]

jobs:
    path-context:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
                name: Build and Publish latest Docker image
                uses: VaultVulp/gp-docker-action@1.1.7
                with:
                    github-token: ${{ secrets.TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
                    image-name: docker-openssh-server # Provide only Docker image name, tag will be automatically set to latest
                    dockerfile: Dockerfile
